export const PropertyField = {
  PropertyFields: [
    {
      label: 'Property Name',
      fieldName: 'propertyName',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Parent Name',
      fieldName: 'parentName',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'City',
      fieldName: 'city',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: false,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'State',
      fieldName: 'state',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: false,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Country',
      fieldName: 'country',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
  ]
};

export const RootUserField = {
  RootUserFields: [
    {
      label: 'First Name',
      fieldName: 'firstName',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Last Name',
      fieldName: 'lastName',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Email',
      fieldName: 'email',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'email',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Phone Number',
      fieldName: 'phoneNumber',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'tel',
      select: false,
      selectOptions: [],
    },
  ]
};

export const TeamMemberField = {
  TeamMemberFields: [
    {
      label: 'First Name',
      fieldName: 'firstName',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Last Name',
      fieldName: 'lastName',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'text',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Email',
      fieldName: 'email',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'email',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Phone Number',
      fieldName: 'phoneNumber',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      type: 'tel',
      select: false,
      selectOptions: [],
    },
    {
      label: 'Role',
      fieldName: 'role',
      errorMessage: 'Required Field',
      helperText: '',
      validator: null,
      validateOnBlur: false,
      fieldSize: 6,
      requiredField: true,
      select: true,
      selectOptions: ['admin', 'user'],
      type: 'text',
    },
  ]
}
